"""Compatibility imports for the optional web-server tracker integration."""

from randovania.game_connection.prime3_tcp_tracker import (
    CLIENT_HELLO,
    CP3W_SERVER_PORT,
    ERROR,
    FRAME_SIZE,
    HEADER,
    MAGIC,
    MAX_CHUNKS,
    PAYLOAD_SIZE,
    SERVER_HELLO_ACK,
    STATUS_OK,
    STATUS_RESYNC,
    TRACKER_ACK,
    TRACKER_DELTA,
    TRACKER_RESYNC_REQUEST,
    TRACKER_SNAPSHOT,
    VERSION,
    Prime3TrackerAdapter,
    Prime3TrackerFrame,
    Prime3TrackerProtocolError,
    Prime3TrackerService,
    Prime3TrackerSession,
)

__all__ = [
    "CLIENT_HELLO",
    "CP3W_SERVER_PORT",
    "ERROR",
    "FRAME_SIZE",
    "HEADER",
    "MAGIC",
    "MAX_CHUNKS",
    "PAYLOAD_SIZE",
    "SERVER_HELLO_ACK",
    "STATUS_OK",
    "STATUS_RESYNC",
    "TRACKER_ACK",
    "TRACKER_DELTA",
    "TRACKER_RESYNC_REQUEST",
    "TRACKER_SNAPSHOT",
    "VERSION",
    "Prime3TrackerAdapter",
    "Prime3TrackerFrame",
    "Prime3TrackerProtocolError",
    "Prime3TrackerService",
    "Prime3TrackerSession",
]
